CommonSettings:
  name: "ProductionConfig"
  enabled: True
  priority: 5

DatabaseConfig:
  db_url: "postgres://user:password@localhost:5432/mydatabase"
  max_connections: 20
  timeout: 60

APIConfig:
  endpoint: "https://api.myservice.com/v1/"
  auth_token: "abcdef123456"
  retries: 5

FeatureFlags:
  experimental_feature: False
  legacy_mode: True

FileStorageConfig:
  storage_path: "/var/app/storage"
  max_size_mb: 500
  backup_enabled: True

AdamConfig:
  type: adam
  learning_rate: 0.001

AttentionConfig:
  use_attention: True
  num_heads: 8
