line-length = 88
target-version = "py311"

[lint]
select = ["ALL"]

ignore = [
    "D100",    # docstring in public module
    "D101",    # docstring
    "D102",    # docstring public method
    "D103",    # docstring in public function
    "D104",    # docstring public packageRuff
    "D105",    # docstring magic function
    "D107",    # docstring __init__
    "TD002",   # missing author in TODO
    "TD003",   # missing issue link for this 
    "TRY003",  # raise-vanilla-args (long messages passed directly to raise)
    "EM101",   # raw-string-in-exception
    "EM102",   # f-string-in-exception
    "COM812",  # missing-trailing-comma
    "PLR0913", # Too many arguments in function definition (8 > 5)
]

[lint.isort]
combine-as-imports = true


[format]
quote-style = "double"
indent-style = "space"
