CommonSettings:
  name: "MyApp Configuration"
  enabled: True
  priority: 5

DatabaseConfig:
  db_url: "postgres://user:password@localhost:5432/mydatabase"
  max_connections: 20
  timeout: 60

APIConfig:
  endpoint: "https://api.myapp.com/v1/"
  auth_token: "abc123securetoken"
  retries: 5

FeatureFlags:
  experimental_feature: True
  legacy_mode: False

FileStorageConfig:
  storage_path: "/var/lib/myapp/storage"
  max_size_mb: 500
  backup_enabled: True

AdamConfig:
  type: adam
  learning_rate: 0.001

AttentionConfig:
  use_attention: True
  num_heads: 8
